### ISSUE TITLE
Help- i d'not see my Heatpump

### ISSUE THREAD

**Issue by fabrydivx** [djbulsink/panasonic_ac#18]
Hi, 
i see ponly two heatpump , i have 4 Ac in my house . 
In Hassio i see that error:

**Comment by djbulsink** [comment]
Hi @fabrydivx,

I've created a quick fix for this problem. Can you test it. By using this file in the custom component: https://github.com/djbulsink/panasonic_ac/blob/fix/heat-pump/custom_components/panasonic_ac/climate.py .

In the future I hope to implement the horizontal airswing.

DJ.

**Comment by JanSkovhus** [comment]
Hi i am getting this error:

Logger: homeassistant.components.climate
Source: custom_components/panasonic_ac/climate.py:113
Integration: Climate (documentation, issues)
First occurred: 1:03:40 PM (1 occurrences)
Last logged: 1:03:40 PM

panasonic_ac: Error on device update!
Traceback (most recent call last):
  File "/config/custom_components/panasonic_ac/climate.py", line 109, in update
    data= self._api.get_device(self._device['id'])
  File "/usr/local/lib/python3.7/site-packages/pcomfortcloud/session.py", line 222, in get_device
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 400 - Data: {"message":"Bad request","code":4008}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/panasonic_ac/climate.py", line 113, in update
    data = self._api.get_device(self._device['id'])
  File "/usr/local/lib/python3.7/site-packages/pcomfortcloud/session.py", line 222, in get_device
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 400 - Data: {"message":"Bad request","code":4008}
