### ISSUE TITLE
Climate Cloud not working

### ISSUE THREAD

**Issue by birdman9876** [djbulsink/panasonic_ac#24]
Howdy,

I've had this integration working in my Home Assistant deployment just fine for quite sometime, however it stopped working for no apparent reason (though, tbh, I keep HA etc pretty up-to-date, so it's possible one of the updates broke it - I just can't directly correlate an update to the break). The logs in HA show this:

> Logger: homeassistant.components.climate
> Source: custom_components/panasonic_ac/climate.py:71
> Integration: Climate (documentation, issues)
> First occurred: 9:14:41 AM (1 occurrences)
> Last logged: 9:14:41 AM
> 
> Error while setting up panasonic_ac platform for climate
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 197, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/panasonic_ac/climate.py", line 71, in setup_platform
>     api.login()
>   File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 99, in login
>     self._create_token()
>   File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 131, in _create_token
>     raise ResponseError(response.status_code, response.text)
> pcomfortcloud.session.ResponseError: Invalid response, status code: 403 - Data: <html>
> <head><title>403 Forbidden</title></head>
> <body>
> <center><h1>403 Forbidden</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>

Any suggestions much appreciated.

**Comment by pcbjonnes** [comment]
My integration also stopped working.

2020-11-03 16:24:04 ERROR (MainThread) [homeassistant.components.climate] panasonic_ac: Error on device update!
Traceback (most recent call last):
File "/config/custom_components/panasonic_ac/climate.py", line 109, in update
data= self._api.get_device(self._device['id'])
File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 290, in get_device
'parameters': self._read_parameters(_json['parameters'])
File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 432, in _read_parameters
value['airSwingHorizontal'] = constants.AirSwingLR(parameters['airSwingLR'])
File "/usr/local/lib/python3.8/enum.py", line 315, in __call__
return cls.__new__(cls, value)
File "/usr/local/lib/python3.8/enum.py", line 617, in __new__
raise ve_exc
ValueError: 5 is not a valid AirSwingLR
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 357, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/panasonic_ac/climate.py", line 113, in update
data = self._api.get_device(self._device['id'])
File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 290, in get_device
'parameters': self._read_parameters(_json['parameters'])
File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 432, in _read_parameters
value['airSwingHorizontal'] = constants.AirSwingLR(parameters['airSwingLR'])
File "/usr/local/lib/python3.8/enum.py", line 315, in __call__
return cls.__new__(cls, value)
File "/usr/local/lib/python3.8/enum.py", line 617, in __new__
raise ve_exc
ValueError: 5 is not a valid AirSwingLR

**Comment by kojax-net** [comment]
You can try to update “manifest.json” file with pcomfortcloud==0.0.17
This file is in config/custom_components/panasonic_ac/
I think you also need to accept the new licence agreement in the panasonic app on your phone

**Comment by pcbjonnes** [comment]
@kojax-net : Did both. That fixed the problem! Thank you!

**Comment by birdman9876** [comment]
> You can try to update “manifest.json” file with pcomfortcloud==0.0.17
> This file is in config/custom_components/panasonic_ac/
> I think you also need to accept the new licence agreement in the panasonic app on your phone

As with @pcbjonnes, that did the trick. Thanks!
