### ISSUE TITLE
New API change breaking app

### ISSUE THREAD

**Issue by gitothy** [djbulsink/panasonic_ac#32]
Unable to get the integration working as of a few days. I have the latest version installed with manifest.json showing pcomfortcloud==0.0.21
I’ve also logged on to the app using the separate account I use for this integration and accepted the new terms 

i did check the old tickets but I think all apply to now fixed, similar, breaks

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/panasonic_cc/__init__.py:79 
Integration: Panasonic Comfort Cloud (documentation) 
First occurred: 3:04:33 AM (1 occurrences) 
Last logged: 3:04:33 AM

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 172, in get_devices
    self.login()
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 401 - Data: {"message":"New version app has been published","code":4106}
```

**Comment by gitothy** [comment]
Fixed with latest version. Many thanks!
